# AWS System Mangager Parameter `AOT_CONFIG_CONTENT` Ref: https://aws-otel.github.io/docs/setup/ecs/config-through-ssm 
# This file is only used with ADOTcollector as a sidecar in the Task Definitions 

extensions:
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Will convert all monotonic, cumulative sums to monotonic, delta sums
  cumulativetodelta:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  resourcedetection:
    detectors:
      - env
      - ecs
      - ec2
  resource:
    attributes:
      - key: TaskDefinitionFamily
        from_attribute: aws.ecs.task.family
        action: insert
      - key: aws.ecs.task.family
        action: delete
      - key: InstanceId
        from_attribute: host.id
        action: insert
      - key: host.id
        action: delete
      - key: TaskARN
        from_attribute: aws.ecs.task.arn
        action: insert
      - key: aws.ecs.task.arn
        action: delete
      - key: TaskDefinitionRevision
        from_attribute: aws.ecs.task.revision
        action: insert
      - key: aws.ecs.task.revision
        action: delete
      - key: LaunchType
        from_attribute: aws.ecs.launchtype
        action: insert
      - key: aws.ecs.launchtype
        action: delete
      - key: ClusterARN
        from_attribute: aws.ecs.cluster.arn
        action: insert
      - key: aws.ecs.cluster.arn
        action: delete
      - key: cloud.provider
        action: delete
      - key: cloud.platform
        action: delete
      - key: cloud.account.id
        action: delete
      - key: cloud.region
        action: delete
      - key: cloud.availability_zone
        action: delete
      - key: aws.log.group.names
        action: delete
      - key: aws.log.group.arns
        action: delete
      - key: aws.log.stream.names
        action: delete
      - key: host.image.id
        action: delete
      - key: host.name
        action: delete
      - key: host.type
        action: delete

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": <NEW_RELIC_LICENSE_KEY>

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection, cumulativetodelta, batch/metrics]
      exporters: [otlp]

  extensions: [health_check]